# Site settings
name: Chiyu Blog
email: imperkings@outlook.com
author: Chiyu
url: chiyu-git.github.io
# resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/chiyu-git
baseurl: ""
description: Simplicity is the best
meta_description: Chiyu Blog | 千悠 仅仅只是为了展示一下笔记 web 前端 javascript
motto: Simplicity is the best .
banner: Simplicity is the best .

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: chiyu-git

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

